---
- name: Execute Dev-Ops script
  hosts: grad-test-remote
  remote_user: vagrant
  become: yes
  become_method: sudo

  tasks:

    - name: Execute Show Version Script
      command: lsb_release -a
      register: os_version

    - name: Print OS Version
      debug: var=os_version.stdout_lines

    - name: Execute Get Update Script
      command: apt-get update

    - name: Execute Get Dist Upgrade Script
      command: apt-get dist-upgrade

    - name: Execute Reboot Script
      command: shutdown -r

    - name: Wait for Machine to come back up
      local_action:
        module: wait_for
          host={{ ansible_ssh_host }}
          port={{ ansible_ssh_port }}
          delay=10

    - name: Execute Uptime Script
      command: uptime
