---
- name: Transfer and execute a script.
  hosts: grad-test-remote
  remote_user: vagrant
  become: yes
  become_method: sudo 

  tasks:
---
- name: Transfer and execute a script.
  hosts: grad-test-remote
  remote_user: vagrant
  become: yes
  become_method: sudo

  tasks:

    - name: Copy script
      copy: src=/home/vagrant/ansible-test/dev-ops-script.sh dest=/home/vagrant$

    - name: Execute the script
      command: sh /home/vagrant/dev-ops-script.sh

#    - name: Execute the script
#      command: sh ~/git/ubuntu-devops/dev-ops-script.sh
       
    - name: Get OS Version
      shell: lsb_release -a
      register: os_version

    - name: Print OS Version
      debug: var=os_version.stdout_lines

    - name: Update Apt Cache
      apt: update_cache=yes

    - name: Upgrade OS
      apt: upgrade=dist

    - name: Reboot Machine
      shell: shutdown -r now
     
    - name: Wait for Machine to come back up
      local_action:
        module: wait_for
          host={{ ansible_ssh_host }}
          port={{ ansible_ssh_port }}
          delay=10

    - name: Get OS Version
      shell: lsb_release -a
      register: os_version

    - name: Print OS Version
      debug: var=os_version.stdout_lines

    - name: Get Uptime
      shell: uptime
      register: result

    - name: Print Uptime
      debug: var=result.stdout_lines
